[package]
name = "rig-ollama-explore"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.7"
futures-util = "0.3.31"
rig-core = "0.24.0"
serde = { version = "1.0.228", features = ["derive"] }
tokio = { version = "1.48.0", features = ["full"] }
